import assert from 'node:assert/strict';
import { test } from 'node:test';
import { ComposerDraft, forgetComposerDraft, getComposerDraft, type Draft } from './drafts';

const draft: Draft = { text: 'Please inspect this file', references: [{ id: 'ref', sessionId: 'logical', path: 'file.txt', name: 'file.txt', kind: 'file', token: '\ue001' }], attachments: [{ id: 'attachment', name: 'image.png', path: '/selected/image.png', source: 'disk', expiresAt: 2000000000000, size: 10, kind: 'image' }] };
test('a logical composer restores text, references, attachments and error after runtime adoption and remount', async () => {
  const logicalKey = 'adoption-regression';
  const home = getComposerDraft(logicalKey);
  home.setDraft(draft);
  let rejectSend!: (error: Error) => void;
  const pendingSend = new Promise<void>((_resolve, reject) => { rejectSend = reject; });
  const operation = home.submit(() => pendingSend);
  const adoptedView = getComposerDraft(logicalKey);
  assert.equal(adoptedView.getSnapshot().busy, true);
  assert.deepEqual(adoptedView.draft, draft);
  rejectSend(new Error('Native prompt rejected'));
  await operation;
  assert.deepEqual(adoptedView.draft, draft);
  assert.equal(adoptedView.getSnapshot().busy, false);
  assert.deepEqual(getComposerDraft(logicalKey).draft.attachments, draft.attachments);
});
test('failure does not erase a newer draft typed while the original send is pending', async () => {
  const store = new ComposerDraft();
  store.setDraft(draft);
  let rejectSend!: (error: Error) => void;
  const pending = new Promise<void>((_resolve, reject) => { rejectSend = reject; });
  const operation = store.submit(() => pending);
  const newer: Draft = { text: 'A different follow-up', attachments: [], references: [] };
  store.setDraft(newer);
  rejectSend(new Error('Rejected'));
  await operation;
  assert.deepEqual(store.draft, newer);
  assert.equal(store.getSnapshot().busy, false);
});
test('successful submission clears only the submitted draft and another logical session stays isolated', async () => {
  const first = new ComposerDraft(), second = new ComposerDraft();
  first.setDraft(draft); second.setDraft({ text: 'Other session', references: [], attachments: [] });
  let finish!: () => void;
  const pending = new Promise<void>(resolve => { finish = resolve; });
  const operation = first.submit(() => pending);
  first.setDraft({ text: 'Next prompt', references: [], attachments: [] });
  finish(); await operation;
  assert.equal(first.draft.text, 'Next prompt');
  assert.equal(first.getSnapshot().error, '');
  assert.equal(first.getSnapshot().busy, false);
  assert.equal(second.draft.text, 'Other session');
});
test('accepted attachments leave a newer draft without consuming its new attachments', async () => {
  const store = new ComposerDraft();
  store.setDraft(draft);
  let finish!: () => void;
  const operation = store.submit(() => new Promise<void>(resolve => { finish = resolve; }));
  const added = { ...draft.attachments[0], id: 'new-attachment' };
  store.setDraft({ ...store.draft, text: 'Edited while waiting', attachments: [...store.draft.attachments, added] });
  finish(); await operation;
  assert.deepEqual(store.draft, { text: 'Edited while waiting', references: [], attachments: [added] });
});
test('fork handoff moves the latest composition without leaving attachment aliases in the original', () => {
  const source = new ComposerDraft(), fork = new ComposerDraft();
  source.setDraft(draft);
  const newer = { ...draft, text: 'Edited during fork startup' };
  source.setDraft(newer);
  source.moveTo(fork, 'fork-startup-editor');
  fork.applyEditor('fork-startup-editor', 'Old native editor text');
  assert.deepEqual(fork.draft, newer);
  assert.deepEqual(source.draft, { text: '', references: [], attachments: [] });
  source.setDraft({ text: 'Back in the original', references: [], attachments: [] });
  assert.deepEqual(fork.draft, newer);
  fork.applyEditor('later-editor-command', 'New explicit editor text');
  assert.equal(fork.draft.text, 'New explicit editor text');
  assert.deepEqual(fork.draft.attachments, newer.attachments);
});
test('forgetting a removed conversation draft preserves another composition and fences its late send', async () => {
  const removed = getComposerDraft('removed-conversation');
  const other = getComposerDraft('retained-conversation');
  removed.setDraft(draft); other.setDraft({ ...draft, text: 'Keep this composition' });
  const { promise, resolve } = Promise.withResolvers<void>();
  const sending = removed.submit(() => promise);
  forgetComposerDraft('removed-conversation');
  resolve(); await sending;
  assert.deepEqual(getComposerDraft('removed-conversation').draft, { text: '', references: [], attachments: [] });
  assert.deepEqual(other.draft, { ...draft, text: 'Keep this composition' });
  forgetComposerDraft('removed-conversation'); forgetComposerDraft('retained-conversation');
});
test('connect then send retains the draft through both admissions and blocks duplicate submission', async () => {
  const store = new ComposerDraft();
  store.setDraft(draft);
  const connected = Promise.withResolvers<void>(), accepted = Promise.withResolvers<void>();
  let connections = 0, sends = 0;
  const operation = store.submit(async submitted => {
    connections++; await connected.promise;
    sends++; assert.deepEqual(submitted, draft); await accepted.promise;
  });
  assert.deepEqual(store.draft, draft);
  assert.equal(store.getSnapshot().busy, true);
  assert.deepEqual(store.getSnapshot().pending,draft);
  await store.submit(async () => { connections++; sends++; });
  assert.equal(connections, 1); assert.equal(sends, 0);
  connected.resolve(); await Promise.resolve();
  assert.equal(sends, 1); assert.deepEqual(store.draft, draft);
  accepted.resolve(); await operation;
  assert.deepEqual(store.draft, { text: '', references: [], attachments: [] });
  assert.equal(store.getSnapshot().busy, false);
  assert.equal(store.getSnapshot().pending,undefined);
});

test('failed warm startup restores the pending draft and permits a deliberate retry', async () => {
  const store=new ComposerDraft();
  store.setDraft(draft);
  const startup=Promise.withResolvers<void>();
  let prompts=0;
  const submitting=store.submit(async()=>{await startup.promise;prompts++;});
  assert.deepEqual(store.getSnapshot().pending,draft);
  startup.reject(new Error('Native startup failed'));
  await submitting;
  assert.equal(prompts,0);
  assert.equal(store.getSnapshot().busy,false);
  assert.equal(store.getSnapshot().pending,undefined);
  assert.deepEqual(store.draft,draft);
  await store.submit(async()=>{prompts++;});
  assert.equal(prompts,1);
  assert.equal(store.draft.text,'');
});
