/** Curated against the installed omp catalog; keys remain visible and searchable. */
export const nativeSettingTitles: Record<string, readonly [string, string]> = {
  'enabledModels': ['启用的模型', 'Enabled models'],
  'enabledProviders': ['启用的提供商', 'Enabled providers'],
  'disabledProviders': ['禁用的提供商', 'Disabled providers'],
  'cycleOrder': ['模型角色切换顺序', 'Model role cycle order'],
  'autoResume': ['自动继续最近会话', 'Resume latest session automatically'],
  'setupVersion': ['初始化配置版本', 'Setup version'],
  'startup.quiet': ['安静启动', 'Quiet startup'],
  'startup.showSplash': ['显示启动画面', 'Show startup splash'],
  'startup.setupWizard': ['启动配置向导', 'Startup setup wizard'],
  'startup.checkUpdate': ['启动时检查更新', 'Check updates at startup'],
  'startup.changelogMode': ['更新说明显示方式', 'Changelog display'],
  'update.channel': ['更新频道', 'Update channel'],
  'marketplace.autoUpdate': ['自动更新扩展市场', 'Update marketplace automatically'],
  'compaction.experimentalContextManagement': ['实验性上下文管理', 'Experimental context management'],
  'compaction.midTurnEnabled': ['允许轮次中压缩', 'Mid-turn compression'],
  'compaction.methodOrder': ['压缩方法优先顺序', 'Compression method order'],
  'compaction.handoffSaveToDisk': ['交接内容保存到磁盘', 'Save handoff to disk'],
  'compaction.remoteStreamingV2Enabled': ['远程流式压缩第二版', 'Remote streaming compression v2'],
  'compaction.asyncEnabled': ['异步压缩', 'Asynchronous compression'],
  'compaction.reserveTokens': ['压缩预留令牌数', 'Reserved compression tokens'],
  'compaction.keepRecentTokens': ['保留近期上下文令牌数', 'Keep recent context tokens'],
  'compaction.autoContinue': ['压缩后自动继续', 'Continue after compression'],
  'compaction.remoteEndpoint': ['远程压缩服务地址', 'Remote compression endpoint'],
  'compaction.v2RetainedMessageBudget': ['第二版压缩保留消息预算', 'V2 retained message budget'],
  'compaction.idleEnabled': ['空闲时压缩', 'Compress while idle'],
  'compaction.idleThresholdTokens': ['空闲压缩令牌阈值', 'Idle compression token threshold'],
  'compaction.idleTimeoutSeconds': ['空闲压缩等待秒数', 'Idle compression delay in seconds'],
  'compaction.supersedeReads': ['替换过期读取结果', 'Supersede old reads'],
  'compaction.dropUseless': ['移除无用上下文', 'Drop unneeded context'],
  'contextPromotion.enabled': ['提升上下文容量', 'Context promotion'],
  'extendedContext': ['扩展上下文', 'Extended context'],
  'branchSummary.enabled': ['生成分支摘要', 'Branch summaries'],
  'branchSummary.reserveTokens': ['分支摘要预留令牌数', 'Branch summary reserved tokens'],
  'memory.backend': ['记忆后端', 'Memory backend'],
  'memories.enabled': ['启用记忆', 'Enable memories'],
  'tools.format': ['工具调用格式', 'Tool call format'],
  'tools.approval': ['工具审批规则', 'Tool approval rules'],
  'tools.maxTimeout': ['工具最长执行时间', 'Maximum tool timeout'],
  'tools.artifactSpillThreshold': ['工具输出转存阈值', 'Artifact spill threshold'],
  'tools.artifactHeadBytes': ['保留输出开头字节数', 'Output head bytes'],
  'tools.artifactTailBytes': ['保留输出末尾字节数', 'Output tail bytes'],
  'tools.artifactTailLines': ['保留输出末尾行数', 'Output tail lines'],
  'tools.outputMaxColumns': ['工具输出最大列数', 'Maximum output columns'],
  'tools.intentTracing': ['记录工具调用意图', 'Trace tool intent'],
  'tools.abortOnFabricatedResult': ['发现伪造工具结果时停止', 'Abort on fabricated tool results'],
  'tools.speculativeExecution.enabled': ['工具推测执行', 'Speculative tool execution'],
  'tools.speculativeExecution.maxInFlight': ['推测执行并发上限', 'Speculative execution concurrency'],
  'bash.enabled': ['启用命令行工具', 'Enable shell tool'],
  'shellPath': ['命令行解释器路径', 'Shell executable path'],
  'bash.allowCompoundCommands': ['允许复合命令', 'Allow compound commands'],
  'bash.autoBackground.enabled': ['自动将命令转为后台任务', 'Background commands automatically'],
  'bash.autoBackground.thresholdMs': ['命令转后台等待毫秒数', 'Background command delay in milliseconds'],
  'bash.direnv': ['加载目录环境变量', 'Load direnv environment'],
  'eval.py': ['启用 Python 执行', 'Enable Python execution'],
  'eval.js': ['启用 JavaScript 执行', 'Enable JavaScript execution'],
  'eval.autoProvision': ['自动准备执行环境', 'Provision execution environments automatically'],
  'python.interpreter': ['Python 解释器', 'Python interpreter'],
  'python.kernelMode': ['Python 内核模式', 'Python kernel mode'],
  'async.enabled': ['启用后台任务', 'Enable background jobs'],
  'async.maxJobs': ['后台任务数量上限', 'Maximum background jobs'],
  'task.isolation.enabled': ['隔离子代理工作区', 'Isolate subagent workspaces'],
  'task.isolation.apply': ['应用隔离工作区更改', 'Apply isolated workspace changes'],
  'task.isolation.merge': ['合并隔离工作区更改', 'Merge isolated workspace changes'],
  'task.isolation.commits': ['保留隔离工作区提交', 'Keep isolated workspace commits'],
  'task.eager': ['主动委派子任务', 'Eager task delegation'],
  'task.batch': ['批量委派子任务', 'Batch task delegation'],
  'task.speculativeLaunch': ['推测启动子代理', 'Speculative subagent launch'],
  'task.enableEffort': ['启用子代理工作强度', 'Enable subagent effort'],
  'task.maxConcurrency': ['子代理并发上限', 'Maximum concurrent subagents'],
  'task.enableLsp': ['子代理语言服务', 'Subagent language service'],
  'task.maxRecursionDepth': ['子代理嵌套深度上限', 'Maximum subagent nesting depth'],
  'task.maxRuntimeMs': ['子代理最长运行毫秒数', 'Maximum subagent runtime in milliseconds'],
  'task.agentIdleTtlMs': ['子代理空闲保留毫秒数', 'Subagent idle lifetime in milliseconds'],
  'task.softRequestBudget': ['子代理请求参考预算', 'Subagent soft request budget'],
  'task.softRequestBudgetNotice': ['子代理预算提醒', 'Subagent budget notice'],
  'task.maxEffort': ['子代理最高工作强度', 'Maximum subagent effort'],
  'task.disabledAgents': ['禁用的子代理', 'Disabled subagents'],
  'task.agentModelOverrides': ['按子代理指定模型', 'Per-subagent model overrides'],
  'task.agentServiceTierOverrides': ['按子代理指定服务层级', 'Per-subagent service tiers'],
  'task.agentCompactionThresholdOverrides': ['按子代理指定压缩阈值', 'Per-subagent compression thresholds'],
  'task.prewalk': ['子代理预扫描', 'Subagent prewalk'],
  'task.agentPrewalk': ['按子代理配置预扫描', 'Per-subagent prewalk'],
  'task.agentAdvisor': ['按子代理配置顾问', 'Per-subagent advisor'],
  'retry.enabled': ['自动重试模型请求', 'Retry model requests automatically'],
  'retry.maxRetries': ['模型请求重试次数上限', 'Maximum model retries'],
  'retry.baseDelayMs': ['首次重试等待毫秒数', 'Initial retry delay in milliseconds'],
  'retry.maxDelayMs': ['重试最长等待毫秒数', 'Maximum retry delay in milliseconds'],
  'retry.waitForUsageReset': ['等待模型额度恢复', 'Wait for usage reset'],
  'retry.modelFallback': ['失败时切换备用模型', 'Fallback model on failure'],
  'retry.fallbackChains': ['备用模型切换链', 'Model fallback chains'],
  'providers.maxInFlightRequests': ['模型请求并发上限', 'Maximum concurrent model requests'],
  'providers.webSearchTimeoutSeconds': ['网页搜索超时秒数', 'Web search timeout in seconds'],
  'providers.streamFirstEventTimeoutSeconds': ['首个流式响应超时秒数', 'First stream event timeout in seconds'],
  'providers.streamIdleTimeoutSeconds': ['流式响应空闲超时秒数', 'Stream idle timeout in seconds'],
  'providers.fetch': ['提供商请求方式', 'Provider fetch configuration'],
  'auth.broker.url': ['认证代理地址', 'Authentication broker URL'],
  'auth.accountPolicies': ['账户使用策略', 'Account policies'],
  'searxng.endpoint': ['SearXNG 搜索服务地址', 'SearXNG endpoint'],
  'browser.cdpUrl': ['浏览器调试地址', 'Browser CDP URL'],
  'temperature': ['生成随机性', 'Temperature'],
  'topP': ['核采样概率', 'Top-p sampling'],
  'topK': ['采样候选数量', 'Top-k sampling'],
  'textVerbosity': ['回答详细程度', 'Answer verbosity'],
  'theme.dark': ['深色终端主题', 'Dark terminal theme'],
  'theme.light': ['浅色终端主题', 'Light terminal theme'],
  'symbolPreset': ['终端符号样式', 'Terminal symbol style'],
  'colorBlindMode': ['终端色觉辅助', 'Terminal color-blind mode'],
  'composer.shape': ['终端输入区布局', 'Terminal composer layout'],
  'composer.tokenRate': ['终端生成速度显示', 'Terminal generation rate'],
  'statusLine.preset': ['终端状态栏预设', 'Terminal status line preset'],
  'statusLine.separator': ['终端状态栏分隔符', 'Terminal status line separator'],
  'statusLine.contextLine': ['终端上下文线样式', 'Terminal context line'],
  'statusLine.sessionAccent': ['终端会话强调色', 'Terminal session accent'],
  'statusLine.transparent': ['透明终端状态栏', 'Transparent terminal status line'],
  'terminal.showImages': ['终端显示图片', 'Show images in terminal'],
  'terminal.showProgress': ['终端显示进度', 'Show progress in terminal'],
  'tui.mouse': ['终端鼠标操作', 'Terminal mouse input'],
  'tui.vimMode': ['终端 Vim 输入模式', 'Terminal Vim input'],
  'tui.hyperlinks': ['终端可点击链接', 'Terminal hyperlinks'],
  'tui.renderMermaid': ['终端渲染 Mermaid 图表', 'Terminal Mermaid rendering'],
  'display.smoothStreaming': ['终端平滑流式显示', 'Terminal smooth streaming'],
  'display.hideToolActivity': ['终端隐藏工具活动', 'Hide terminal tool activity'],
};
