/** Unified navigation and its shared shortcut vocabulary. */
export const paletteMessages: Record<'en' | 'zh-CN', Record<string, string>> = {
  en: {
    'omp.palette.title': 'Find anything', 'omp.palette.placeholder': 'Search anything…  > actions  / commands  @ files  # messages',
    'omp.palette.scopes': 'Search scope', 'omp.palette.scope.all': 'All', 'omp.palette.scope.sessions': 'Sessions', 'omp.palette.scope.messages': 'Messages', 'omp.palette.scope.files': 'Files', 'omp.palette.scope.commands': 'Commands', 'omp.palette.scope.settings': 'Settings', 'omp.palette.scope.actions': 'Actions',
    'omp.palette.preview': 'Preview', 'omp.palette.loading': 'Searching…', 'omp.palette.empty': 'No matches. Try a different phrase or scope.', 'omp.palette.messageHint': 'Search the words inside your conversations.', 'omp.palette.navigation': '↑ ↓ to navigate · Enter to open · Esc to close', 'omp.palette.truncated': 'Showing the closest results. Refine your search for more.', 'omp.palette.diagnostics': 'Search details ({{count}})', 'omp.palette.filePreviewUnavailable': 'Preview unavailable for this file. Open it in the file panel.', 'omp.palette.settingsHint': 'Open Settings with this filter', 'omp.palette.helpNote': 'Use ? outside text fields to open this guide. Global combinations also work while editing.', 'omp.palette.role.user': 'You', 'omp.palette.role.assistant': 'Assistant',
    'omp.palette.setting.font': 'Font', 'omp.palette.setting.language': 'Language', 'omp.palette.setting.model': 'Model', 'omp.palette.setting.thinking': 'Thinking', 'omp.palette.setting.credentials': 'Credentials', 'omp.palette.setting.profile': 'Profile',
    'omp.palette.action.new-session': 'New session', 'omp.palette.action.open-workspace': 'Open workspace', 'omp.palette.action.palette': 'Find anything', 'omp.palette.action.quick-open': 'Find a file', 'omp.palette.action.search-messages': 'Search all messages', 'omp.palette.action.find': 'Find in conversation', 'omp.palette.action.toggle-sidebar': 'Toggle sidebar', 'omp.palette.action.toggle-panel': 'Toggle work panel', 'omp.palette.action.settings': 'Settings', 'omp.palette.action.shortcuts': 'Keyboard shortcuts', 'omp.palette.action.close-tab': 'Close current view', 'omp.palette.action.next-tab': 'Next conversation', 'omp.palette.action.prev-tab': 'Previous conversation', 'omp.palette.action.jump-latest': 'Jump to latest', 'omp.palette.action.stop': 'Stop current run', 'omp.palette.action.open-files': 'Open Files', 'omp.palette.action.open-changes': 'Open Changes', 'omp.palette.action.open-tasks': 'Open Tasks', 'omp.palette.action.open-session': 'Open Session details',
    'omp.palette.description.new-session': 'Start a conversation in the current workspace.', 'omp.palette.description.open-workspace': 'Choose a project folder.', 'omp.palette.description.palette': 'Search sessions, messages, files, commands, settings and actions.', 'omp.palette.description.quick-open': 'Search files in the current workspace.', 'omp.palette.description.search-messages': 'Find words across saved conversation history.', 'omp.palette.description.find': 'Search the content loaded in this conversation.', 'omp.palette.description.toggle-sidebar': 'Show or hide conversation navigation.', 'omp.palette.description.toggle-panel': 'Show or hide the work panel.', 'omp.palette.description.settings': 'Change appearance, runtime and model preferences.', 'omp.palette.description.shortcuts': 'Browse every application shortcut.', 'omp.palette.description.close-tab': 'Close the foreground overlay, settings or panel; otherwise return Home. Running work continues.', 'omp.palette.description.next-tab': 'Select the next conversation in the sidebar.', 'omp.palette.description.prev-tab': 'Select the previous conversation in the sidebar.', 'omp.palette.description.jump-latest': 'Return to the newest content and follow updates.', 'omp.palette.description.stop': 'Interrupt the current conversation’s active run.', 'omp.palette.description.open-files': 'Browse workspace files.', 'omp.palette.description.open-changes': 'Review workspace changes.', 'omp.palette.description.open-tasks': 'Explore delegated tasks.', 'omp.palette.description.open-session': 'Inspect this conversation’s model and context.',
  },
  'zh-CN': {
    'omp.palette.title': '查找任何内容', 'omp.palette.placeholder': '搜索任何内容…  > 动作  / 命令  @ 文件  # 消息',
    'omp.palette.scopes': '搜索范围', 'omp.palette.scope.all': '全部', 'omp.palette.scope.sessions': '会话', 'omp.palette.scope.messages': '消息', 'omp.palette.scope.files': '文件', 'omp.palette.scope.commands': '命令', 'omp.palette.scope.settings': '设置', 'omp.palette.scope.actions': '动作',
    'omp.palette.preview': '预览', 'omp.palette.loading': '搜索中…', 'omp.palette.empty': '没有匹配内容，试试其他关键词或范围。', 'omp.palette.messageHint': '输入关键词，查找对话中的内容。', 'omp.palette.navigation': '↑ ↓ 选择 · Enter 打开 · Esc 关闭', 'omp.palette.truncated': '已显示部分结果，缩小搜索范围可找到更多。', 'omp.palette.diagnostics': '搜索详情（{{count}}）', 'omp.palette.filePreviewUnavailable': '此文件无法预览，可在文件面板中打开。', 'omp.palette.settingsHint': '打开设置并筛选此项', 'omp.palette.helpNote': '在输入框外按 ? 也可打开此指南。全局组合键在编辑时同样可用。', 'omp.palette.role.user': '你', 'omp.palette.role.assistant': '助手',
    'omp.palette.setting.font': '字体', 'omp.palette.setting.language': '语言', 'omp.palette.setting.model': '模型', 'omp.palette.setting.thinking': '思考', 'omp.palette.setting.credentials': '凭据', 'omp.palette.setting.profile': 'profile',
    'omp.palette.action.new-session': '新建会话', 'omp.palette.action.open-workspace': '打开工作目录', 'omp.palette.action.palette': '查找任何内容', 'omp.palette.action.quick-open': '查找文件', 'omp.palette.action.search-messages': '搜索全部消息', 'omp.palette.action.find': '在对话中查找', 'omp.palette.action.toggle-sidebar': '切换侧边栏', 'omp.palette.action.toggle-panel': '切换工作面板', 'omp.palette.action.settings': '设置', 'omp.palette.action.shortcuts': '键盘快捷键', 'omp.palette.action.close-tab': '关闭当前视图', 'omp.palette.action.next-tab': '下一个会话', 'omp.palette.action.prev-tab': '上一个会话', 'omp.palette.action.jump-latest': '回到最新', 'omp.palette.action.stop': '停止当前运行', 'omp.palette.action.open-files': '打开文件', 'omp.palette.action.open-changes': '打开变更', 'omp.palette.action.open-tasks': '打开任务', 'omp.palette.action.open-session': '打开会话详情',
    'omp.palette.description.new-session': '在当前工作目录中开始新对话。', 'omp.palette.description.open-workspace': '选择一个项目文件夹。', 'omp.palette.description.palette': '查找会话、消息、文件、命令、设置和动作。', 'omp.palette.description.quick-open': '搜索当前工作目录中的文件。', 'omp.palette.description.search-messages': '搜索全部历史对话中的内容。', 'omp.palette.description.find': '查找当前对话中已加载的内容。', 'omp.palette.description.toggle-sidebar': '显示或隐藏会话导航。', 'omp.palette.description.toggle-panel': '显示或隐藏工作面板。', 'omp.palette.description.settings': '调整外观、运行环境和模型偏好。', 'omp.palette.description.shortcuts': '查看所有应用快捷键。', 'omp.palette.description.close-tab': '关闭浮层、设置或工作面板，否则回到主页。运行中的任务不会停止。', 'omp.palette.description.next-tab': '选择侧边栏中的下一个会话。', 'omp.palette.description.prev-tab': '选择侧边栏中的上一个会话。', 'omp.palette.description.jump-latest': '回到最新内容并跟随更新。', 'omp.palette.description.stop': '中断当前会话正在进行的任务。', 'omp.palette.description.open-files': '浏览工作目录中的文件。', 'omp.palette.description.open-changes': '查看工作目录中的变更。', 'omp.palette.description.open-tasks': '查看委派的任务。', 'omp.palette.description.open-session': '查看此会话的模型与上下文。',
  },
};
