import { writeFileSync } from 'node:fs';
export const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
export async function until(fn, label, timeout = 30000) { const end = Date.now() + timeout; let last; do { last = await fn(); if (last) return last; await sleep(80); } while (Date.now() < end); throw new Error(`Timed out: ${label}`); }
export class CDP {
  static async connect(url) { const c = new CDP(); c.socket = new WebSocket(url); await new Promise((resolve, reject) => { c.socket.onopen = resolve; c.socket.onerror = reject; }); c.socket.onmessage = event => { const p = JSON.parse(String(event.data)); if (p.method) { for (const listener of c.listeners.get(p.method) ?? []) listener(p.params); return; } const task = c.pending.get(p.id); if (!task) return; c.pending.delete(p.id); clearTimeout(task.timer); p.error ? task.reject(new Error(JSON.stringify(p.error))) : task.resolve(p.result); }; return c; }
  pending = new Map(); sequence = 0; listeners = new Map();
  on(method, listener) { const listeners = this.listeners.get(method) ?? new Set(); listeners.add(listener); this.listeners.set(method, listeners); return () => listeners.delete(listener); }
  call(method, params = {}) { return new Promise((resolve, reject) => { const id = ++this.sequence; const timer = setTimeout(() => { this.pending.delete(id); reject(new Error(`CDP timeout: ${method}`)); }, 15000); this.pending.set(id, { resolve, reject, timer }); this.socket.send(JSON.stringify({ id, method, params })); }); }
  async eval(expression) { const r = await this.call('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (r.exceptionDetails) throw new Error(JSON.stringify(r.exceptionDetails)); return r.result.value; }
  async key(key = 'Enter') { const code = key === 'Enter' ? 13 : key === 'Escape' ? 27 : 0; for (const type of ['keyDown', 'keyUp']) await this.call('Input.dispatchKeyEvent', { type, key, code: key, windowsVirtualKeyCode: code }); }
  async click(selector, text) { const clicked = await this.eval(`(() => { const e = [...document.querySelectorAll(${JSON.stringify(selector)})].find(e => e.getBoundingClientRect().width && !e.disabled && (${text === undefined ? 'true' : `e.textContent.trim() === ${JSON.stringify(text)}`})); if (!e) return false; e.scrollIntoView({block:'nearest'}); e.focus({preventScroll:true}); e.click(); return true; })()`); if (!clicked) throw new Error(`Visible control missing: ${selector} ${text ?? ''}`); }
  async clickName(name, selector = 'button,[role=button],[role=menuitem],[role=switch]') { const clicked = await this.eval(`(() => { const e = [...document.querySelectorAll(${JSON.stringify(selector)})].find(e => e.getBoundingClientRect().width && !e.disabled && (e.getAttribute('aria-label') || e.innerText.trim()) === ${JSON.stringify(name)}); if (!e) return false; e.scrollIntoView({block:'nearest'}); e.focus({preventScroll:true}); e.click(); return true; })()`); if (!clicked) throw new Error(`Accessible control missing: ${name} (${selector})`); }
  async shot(path) { const { data } = await this.call('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false }); writeFileSync(path, Buffer.from(data, 'base64')); }
  close() { this.socket.close(); for (const task of this.pending.values()) { clearTimeout(task.timer); task.reject(new Error('CDP closed')); } this.pending.clear(); }
}
