export const installProbe = `(() => {
  window.__e2e = {frames:[],longTasks:[],acceptance:[],gaps:[],tracking:false,prompt:'',started:performance.now()};
  new PerformanceObserver(list => { for(const e of list.getEntries()) window.__e2e.longTasks.push({at:e.startTime,duration:e.duration}); }).observe({type:'longtask',buffered:true});
  document.addEventListener('wheel',()=>{window.__e2e.userScrolling=true},{capture:true,passive:true});
  document.addEventListener('click',event=>{if(event.target.closest?.('.live-status-row[data-state] > button.live-status-main,.live-status-return'))window.__e2e.userScrolling=false},true);
  let previous; function tick(now){const p=window.__e2e;const running=!!document.querySelector('.stop-btn');if(previous&&running)p.frames.push(now-previous);previous=now;
  const s=document.querySelector('.thread-scroll');if(s&&running&&!p.userScrolling&&document.querySelector('.thread-wrap[data-following=true]'))p.gaps.push({at:now,gap:s.scrollHeight-s.clientHeight-s.scrollTop});
  if(p.tracking){const accepted=[...document.querySelectorAll('.thread-scroll .message-row')].some(e=>e.innerText.includes(p.prompt));const rows=[...document.querySelectorAll('.thread-item')];const row=rows.find(e=>e.classList.contains('active'));const r=row?.getBoundingClientRect();p.acceptance.push({at:now,accepted,rows:rows.length,title:row?.innerText,project:row?.closest('.project-group')?.querySelector('.omp-project-disclosure')?.title,rect:r?{x:r.x,y:r.y,width:r.width,height:r.height}:null});}requestAnimationFrame(tick);}requestAnimationFrame(tick);return true;})()`;
export const snapshot = `(() => {const box=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height}};return {text:document.body.innerText,elements:[...document.querySelectorAll('button,[role=alert],[role=status],[data-state],.thread-item,[role=textbox],.composer-model-thinking-chip')].filter(e=>e.getBoundingClientRect().width).map(e=>({tag:e.tagName,role:e.getAttribute('role'),state:e.getAttribute('data-state'),label:e.getAttribute('aria-label'),text:e.innerText,disabled:e.disabled,rect:box(e)}))}})()`;
